### ISSUE TITLE
The issue in segmentation

### ISSUE THREAD

**Issue by FeiyangWu6** [iMoonLab/DeepHypergraph#4]
Your work is amazing! I think it is helpful for me! Thank you very much!
There is a segmentation network for heart mri in your example work. However, I wonder why the lable is two-dimensional as the heart mri is three_dimensional? How do you process the lable?

**Comment by yifanfeng97** [comment]
Thanks for your attention. 
Here, the image segmentation task has been transformed into the image patch classification task. Thus we reshape the MxNxC MRI data into MNxC. The label is also reshaped. The purpose of this operation is to match the hypergraph convolution, which is always convolute the NxC1 node feature into the NxC2 node feature.
Hopes it can help you.

**Comment by FeiyangWu6** [comment]
Thanks for your reply.
But I still wonder how to reshape the MxNxC label to MNx1 ? Does this action loss some local information? 
And have you ever encountered the problem that  matrix is so large that out of memory?

**Comment by yifanfeng97** [comment]
The reshape operation is necessary for graph/hypergraph convolution. Because the input of graph/hypergraph convolution is always NxC, where N denotes node number and C denotes feature dimension. The action may lose local structure neighbor information. However, in hypergraph convolution, the neighbor information can also be modeled with the hypergraph incidence matrix.

**Comment by yifanfeng97** [comment]
We are back with a new version DHG. Welcome to try!
